### ISSUE TITLE
How to run Inpainting / Downstream Tasks

### ISSUE THREAD

**Issue by mashrurmorshed** [VinAIResearch/LFM#13]
Hi guys,

I've checked out your class conditional generation (imagenet) and unconditional synthesis (celeba 512) and the results seem very promising. However, I am having trouble evaluating the downstream tasks.

Could you update / give clear instructions on how to run the inpainting downstream task? (for example, on CelebA-HQ 256?).

The args given in the readme don't all seem to match with the code in  `downstream_tasks/test_flow_latent_inpainting.py` (for instance, the argparse accepts `epoch_id`, not `num_epoch`).

It also seems that there is a separate checkpoint used for CelebA Inpainting (i.e. model_500.pth) that is not given.

Thanks!

**Comment by thanksforyourworks** [comment]
Hello! I am also trying to run inpainting, have you mastered the command to run this downstream task? If yes, could you guide me what the exact command is, i would appreciate it. Thank you for your time.
